repository: ContinuousTeacherStudent/ContinuousTeacherStudent.github.io
theme: jekyll-theme-slate
title: Teacher-Student Automated Curriculum Learning in Continuously Parameterized Environments
description: Additional videos for CoRL 2019 paper submission
